### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lostmates** [LD31D/planfix_py#7] opened 2023-06-21 09:21 UTC
Is it possile to create tasks in planfix via this repo?
And how to do it if yes?
thx :D

**Comment by LD31D** [comment] 2023-06-21 09:54
Hello, @lostmates, I have abandoned work on this library.

If you want to create a task in PF you can work directly with the PF API - https://planfix.com/ru/help/REST_API

Here is an example of how to create a task using PF RestAPI:

```
import requests

PF_ACCOUNT = ''
PF_API_TOKEN = ''

url = f"https://{PF_ACCOUNT}.planfix.com/rest/task/"

headers = {
	'Authorization': f"Bearer {PF_API_TOKEN}"
}

data = {
	'name': 'Test Task Title'
}

response = requests.post(url, json=data, headers=headers)
print(response.json())
```

You can find more examples of request generation at this link - https://help.planfix.com/restapidocs/
Duplicate of #

**Closed as completed** 2023-06-23 17:47 UTC
